trigger:
- main
- feature/*

pool:
  vmImage: ubuntu-latest

steps:

- task: NodeTool@1
  inputs:
    versionSpec: '18.x'
  displayName: 'Install Node.js'

- script: |
    node -v
    npm -v
  displayName: 'Check Versions'

- script: npm ci
  displayName: 'Clean Install Dependencies'
  
- script: npm test
  displayName: 'Run Jest Tests'
